<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="assets/css/bootstrap.css">
		<script type="text/javascript" src="js/jquery.js"></script>
		<script type="text/javascript" src="js/bootstrap.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<div class="navbar-brand">My Website</div>
				</div>
				<ul class="nav navbar-nav">
					<li><a href="#">Home</a></li>
					<li><a href="#">Profile</a></li>
					<li><a href="#">About Me</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#"><span class="glyphicon glyphicon-user"></span>Daftar</a></li>
					<li><a href="#"><span class="glyphicon glyphicon-login"></span>Login</a></li>
				</ul>
			</div>
		</nav><br/><br/><br/>
		<h3>ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
		ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
		ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
		ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
		ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
		ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
	ADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHASADSIBHAIKSUDOASHDOASHDOASIHDOIASHDIOHASODHAS
			
		</h4>
	</body>
</html>